name: 'Release to Twitter Workflow'
# Trigger on release
on:
  release:
    types:
      - published
jobs:
  test:
    name: posting_on_twitter
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Twittction
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
            twitter_status: "[New Release] SharepointPlus ${{github.event.release.tag_name}} – review the changelog at ${{github.event.release.html_url}}"
            twitter_consumer_key: ${{ secrets.TWITTER_API_KEY }}
            twitter_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
